version: '3.3'
services:

  cards:
    container_name: cards
    image: 656fa1670f44
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/test || exit 1"] # http://localhost:8080
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "no"
    ports:
      # <Port exposed> : < Port running inside container>
      - '8080:8080'

  player:
    container_name: player
    image: 7831e8ea04f0
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8081/test || exit 1"]
      interval: 30s
      timeout: 1000s
      retries: 5
    restart: "no"
    ports:
      # <Port exposed> : < Port running inside container>
      - '8081:8081'
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql11/data
      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

  Schwimmen:
    container_name: Schwimmen
    image: b9a792c49387
    restart: "no"

volumes:
  db:
    driver: local